### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by loostrum** [davidgardenier/frbcat#7]
A new release to pypi would be useful as the current release doesn't work anymore for the TNS.
I'd add a file to the repo so it publishes to pypi automatically when you create a Github release.
I'm happy to do it if you agree.

**Comment by davidgardenier** [comment]
That would be very useful (Github actions?). Let me know what you might need from me.

**Comment by loostrum** [comment]
Great, yes it would be through Github actions. You'd need to create an API token with upload rights on PyPI and store in in the repo, see [here](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/). Or you could share the PyPI project with me (maintainer access should be enough, I think).

**Comment by davidgardenier** [comment]
Can you actually also add an automatic Github version release upon any changes to the repository, so that even that step is automated?

**Comment by loostrum** [comment]
Yep that works, it could be done on e.g. every push to master.

**Comment by loostrum** [comment]
Added auto-release (Github + pypi) on any push to the master branch. By default, the patch version number is updated (e.g. 0.2.16 to 0.2.17). If you use any of the release:major/minor/patch or norelease labels on a PR, the version will be updated accordingly (or no release is generated at all). The __version__.py file contains "github" by default, so that's the version people see when they install from Github. The proper version number is there when installing from PyPI. This was the only way I knew how to automatically update the version number in setup.py
